In [1]:
import pandas as pd

df = pd.read_csv("Sample - Superstore.csv", encoding="latin1")

df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [2]:
print("Dataset Shape:")
print(df.shape)

print("\nFirst 5 Rows:")
display(df.head())

print("\nLast 5 Rows:")
display(df.tail())

print("\nColumn Names:")
print(df.columns.tolist())

print("\nData Types:")
print(df.dtypes)

Dataset Shape:
(9994, 21)

First 5 Rows:

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

Last 5 Rows:

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
9989,9990,CA-2014-110422,1/21/2014,1/23/2014,Second Class,TB-21400,Tom Boeckenhauer,Consumer,United States,Miami,...,33180,South,FUR-FU-10001889,Furniture,Furnishings,Ultra Door Pull Handle,25.248,3,0.2,4.1028
9990,9991,CA-2017-121258,2/26/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,FUR-FU-10000747,Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.960,2,0.0,15.6332
9991,9992,CA-2017-121258,2/26/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,TEC-PH-10003645,Technology,Phones,Aastra 57i VoIP phone,258.576,2,0.2,19.3932
9992,9993,CA-2017-121258,2/26/2017,3/3/2017,Standard Class,DB-13060,Dave Brooks,Consumer,United States,Costa Mesa,...,92627,West,OFF-PA-10004041,Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.600,4,0.0,13.3200
9993,9994,CA-2017-119914,5/4/2017,5/9/2017,Second Class,CC-12220,Chris Cortes,Consumer,United States,Westminster,...,92683,West,OFF-AP-10002684,Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.160,2,0.0,72.9480

Column Names:
['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode', 'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State', 'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category', 'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit']

Data Types:
Row ID             int64
Order ID          object
Order Date        object
Ship Date         object
Ship Mode         object
Customer ID       object
Customer Name     object
Segment           object
Country           object
City              object
State             object
Postal Code        int64
Region            object
Product ID        object
Category          object
Sub-Category      object
Product Name      object
Sales            float64
Quantity           int64
Discount         float64
Profit           float64
dtype: object

In [3]:
print("Missing Values in Each Column:")
print(df.isnull().sum())

Missing Values in Each Column:
Row ID           0
Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Country          0
City             0
State            0
Postal Code      0
Region           0
Product ID       0
Category         0
Sub-Category     0
Product Name     0
Sales            0
Quantity         0
Discount         0
Profit           0
dtype: int64

In [4]:
# Handling missing values
# Since there are no missing values, this step confirms the dataset is already clean in this part.

df = df.dropna()

print("Missing values after handling:")
print(df.isnull().sum())

print("\nDataset shape after handling missing values:", df.shape)

Missing values after handling:
Row ID           0
Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Country          0
City             0
State            0
Postal Code      0
Region           0
Product ID       0
Category         0
Sub-Category     0
Product Name     0
Sales            0
Quantity         0
Discount         0
Profit           0
dtype: int64

Dataset shape after handling missing values: (9994, 21)

In [5]:
print("Rows before removing duplicates:", df.shape[0])

df = df.drop_duplicates()

print("Rows after removing duplicates:", df.shape[0])
print("Duplicate rows remaining:", df.duplicated().sum())

Rows before removing duplicates: 9994
Rows after removing duplicates: 9994
Duplicate rows remaining: 0

In [6]:
# Filtering records where Sales is greater than 100

filtered_df = df[df["Sales"] > 100]

print("Original dataset shape:", df.shape)
print("Filtered dataset shape where Sales > 100:", filtered_df.shape)

filtered_df.head()

Original dataset shape: (9994, 21)
Filtered dataset shape where Sales > 100: (3765, 21)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
7,8,CA-2014-115812,6/9/2014,6/14/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,TEC-PH-10002275,Technology,Phones,Mitel 5320 IP Phone VoIP phone,907.1520,6,0.20,90.7152
9,10,CA-2014-115812,6/9/2014,6/14/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,OFF-AP-10002892,Office Supplies,Appliances,Belkin F5C206VTEL 6 Outlet Surge,114.9000,5,0.00,34.4700

In [7]:
# Selecting important columns from the dataset

selected_columns = df[[
    "Order ID",
    "Order Date",
    "Customer Name",
    "Category",
    "Sub-Category",
    "Product Name",
    "Sales",
    "Quantity",
    "Profit"
]]

print("Selected columns shape:", selected_columns.shape)

selected_columns.head()

Selected columns shape: (9994, 9)

,Order ID,Order Date,Customer Name,Category,Sub-Category,Product Name,Sales,Quantity,Profit
0,CA-2016-152156,11/8/2016,Claire Gute,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,41.9136
1,CA-2016-152156,11/8/2016,Claire Gute,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,219.5820
2,CA-2016-138688,6/12/2016,Darrin Van Huff,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,6.8714
3,US-2015-108966,10/11/2015,Sean O'Donnell,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,-383.0310
4,US-2015-108966,10/11/2015,Sean O'Donnell,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,2.5164

In [8]:
# Creating a new column: total_amount = price * quantity

df["Price"] = df["Sales"] / df["Quantity"]

df["total_amount"] = df["Price"] * df["Quantity"]

df[["Product Name", "Sales", "Quantity", "Price", "total_amount"]].head()

,Product Name,Sales,Quantity,Price,total_amount
0,Bush Somerset Collection Bookcase,261.9600,2,130.9800,261.9600
1,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,243.9800,731.9400
2,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,7.3100,14.6200
3,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,191.5155,957.5775
4,Eldon Fold 'N Roll Cart System,22.3680,2,11.1840,22.3680

In [9]:
# Saving the cleaned dataset as a new CSV file

df.to_csv("cleaned_superstore.csv", index=False)

print("Cleaned dataset saved successfully as cleaned_superstore.csv")
print("Final dataset shape:", df.shape)

Cleaned dataset saved successfully as cleaned_superstore.csv
Final dataset shape: (9994, 23)

In [10]:
summary = f"""
Data Cleaning Summary:

1. Loaded the Superstore dataset using Pandas.
2. Explored the dataset using head, tail, shape, columns, and data types.
3. Checked missing values in all columns.
4. Handled missing values using dropna because no null values were present.
5. Removed duplicate rows from the dataset.
6. Performed filtering by selecting records where Sales > 100.
7. Selected important columns such as Order ID, Product Name, Sales, Quantity, and Profit.
8. Created a new column named Price using Sales / Quantity.
9. Created a new column named total_amount using Price * Quantity.
10. Saved the cleaned dataset as cleaned_superstore.csv.

Final Dataset Shape: {df.shape}
"""

print(summary)

Data Cleaning Summary:

1. Loaded the Superstore dataset using Pandas.
2. Explored the dataset using head, tail, shape, columns, and data types.
3. Checked missing values in all columns.
4. Handled missing values using dropna because no null values were present.
5. Removed duplicate rows from the dataset.
6. Performed filtering by selecting records where Sales > 100.
7. Selected important columns such as Order ID, Product Name, Sales, Quantity, and Profit.
8. Created a new column named Price using Sales / Quantity.
9. Created a new column named total_amount using Price * Quantity.
10. Saved the cleaned dataset as cleaned_superstore.csv.

Final Dataset Shape: (9994, 23)

# Assignment Summary

- Loaded dataset using pandas
- Explored dataset structure
- Checked missing values
- Removed duplicates
- Filtered high-rated products
- Created saved_amount column
- Saved cleaned dataset