In [1]:
print("Hello")

Hello

In [2]:
import pandas as pd

In [3]:
import os
os.listdir()

['.venv',
 '.venv-1',
 '.venv-2',
 '.vscode',
 'archive (2)',
 'archive (2).zip',
 'assignment.ipynb']

In [4]:
os.listdir("archive (2)")

['backpacks.csv',
 'bath-robe.csv',
 'bath-towels.csv',
 'bathroom-accessories.csv',
 'bedsheets.csv',
 'belts.csv',
 'bodysuit.csv',
 'boots.csv',
 'boxers.csv',
 'bra.csv',
 'bracelet.csv',
 'briefs.csv',
 'camisoles.csv',
 'candle-holders.csv',
 'caps.csv',
 'casual-shoes.csv',
 'chair-cover.csv',
 'clothing-set.csv',
 'clutches.csv',
 'co-ords.csv',
 'Combined_dataset.csv',
 'curtains-and-sheers.csv',
 'cutlery.csv',
 'dinnerware.csv',
 'dresses.csv',
 'duffel-bag.csv',
 'dungarees.csv',
 'dupatta.csv',
 'earrings.csv',
 'ethnic-dresses.csv',
 'face-moisturisers.csv',
 'face-wash-and-cleanser.csv',
 'flats.csv',
 'flip-flops.csv',
 'floor-mats--dhurries.csv',
 'formal-shoes.csv',
 'foundation.csv',
 'gloves.csv',
 'hair-accessory.csv',
 'hair-brush-and-comb.csv',
 'hair-cream-and-mask.csv',
 'hair-masks.csv',
 'handbags.csv',
 'headphones.csv',
 'heels.csv',
 'home-fragrance-set.csv',
 'innerwear-vests.csv',
 'jackets.csv',
 'jeans.csv',
 'jumpsuit.csv',
 'kurta-sets.csv',
 'kurtas.csv',
 'kurtis.csv',
 'lipstick.csv',
 'lounge-pants.csv',
 'lounge-shorts.csv',
 'lounge-tshirts.csv',
 'mangalsutra.csv',
 'mobile-accessories.csv',
 'night-suits.csv',
 'nightdress.csv',
 'outdoor-masks.csv',
 'palazzos.csv',
 'perfume-and-body-mist.csv',
 'pillow-covers.csv',
 'README.md',
 'ring.csv',
 'runners.csv',
 'sandals.csv',
 'saree-blouse.csv',
 'sarees.csv',
 'scarves.csv',
 'shampoo-and-conditioner.csv',
 'shaving-essentials.csv',
 'sherwani.csv',
 'shirts.csv',
 'shorts.csv',
 'showpieces.csv',
 'skirts.csv',
 'sports-shoes.csv',
 'sunglasses.csv',
 'sweaters.csv',
 'sweatshirts.csv',
 'swim-tops.csv',
 'table-covers.csv',
 'thermal-bottoms.csv',
 'tights.csv',
 'tops.csv',
 'towel-set.csv',
 'track-pants.csv',
 'trolley-bag.csv',
 'trousers.csv',
 'trunk.csv',
 'tshirts.csv',
 'tunics.csv',
 'wall-art.csv',
 'wallets.csv',
 'watches.csv',
 'yoga-mats.csv']

In [5]:
import pandas as pd

df = pd.read_csv("archive (2)/shopping_trends.csv")

FileNotFoundError: [Errno 2] No such file or directory: 'archive (2)/shopping_trends.csv'

In [6]:
os.listdir("archive (2)")

['backpacks.csv',
 'bath-robe.csv',
 'bath-towels.csv',
 'bathroom-accessories.csv',
 'bedsheets.csv',
 'belts.csv',
 'bodysuit.csv',
 'boots.csv',
 'boxers.csv',
 'bra.csv',
 'bracelet.csv',
 'briefs.csv',
 'camisoles.csv',
 'candle-holders.csv',
 'caps.csv',
 'casual-shoes.csv',
 'chair-cover.csv',
 'clothing-set.csv',
 'clutches.csv',
 'co-ords.csv',
 'Combined_dataset.csv',
 'curtains-and-sheers.csv',
 'cutlery.csv',
 'dinnerware.csv',
 'dresses.csv',
 'duffel-bag.csv',
 'dungarees.csv',
 'dupatta.csv',
 'earrings.csv',
 'ethnic-dresses.csv',
 'face-moisturisers.csv',
 'face-wash-and-cleanser.csv',
 'flats.csv',
 'flip-flops.csv',
 'floor-mats--dhurries.csv',
 'formal-shoes.csv',
 'foundation.csv',
 'gloves.csv',
 'hair-accessory.csv',
 'hair-brush-and-comb.csv',
 'hair-cream-and-mask.csv',
 'hair-masks.csv',
 'handbags.csv',
 'headphones.csv',
 'heels.csv',
 'home-fragrance-set.csv',
 'innerwear-vests.csv',
 'jackets.csv',
 'jeans.csv',
 'jumpsuit.csv',
 'kurta-sets.csv',
 'kurtas.csv',
 'kurtis.csv',
 'lipstick.csv',
 'lounge-pants.csv',
 'lounge-shorts.csv',
 'lounge-tshirts.csv',
 'mangalsutra.csv',
 'mobile-accessories.csv',
 'night-suits.csv',
 'nightdress.csv',
 'outdoor-masks.csv',
 'palazzos.csv',
 'perfume-and-body-mist.csv',
 'pillow-covers.csv',
 'README.md',
 'ring.csv',
 'runners.csv',
 'sandals.csv',
 'saree-blouse.csv',
 'sarees.csv',
 'scarves.csv',
 'shampoo-and-conditioner.csv',
 'shaving-essentials.csv',
 'sherwani.csv',
 'shirts.csv',
 'shorts.csv',
 'showpieces.csv',
 'skirts.csv',
 'sports-shoes.csv',
 'sunglasses.csv',
 'sweaters.csv',
 'sweatshirts.csv',
 'swim-tops.csv',
 'table-covers.csv',
 'thermal-bottoms.csv',
 'tights.csv',
 'tops.csv',
 'towel-set.csv',
 'track-pants.csv',
 'trolley-bag.csv',
 'trousers.csv',
 'trunk.csv',
 'tshirts.csv',
 'tunics.csv',
 'wall-art.csv',
 'wallets.csv',
 'watches.csv',
 'yoga-mats.csv']

In [7]:
import pandas as pd

df = pd.read_csv("archive (2)/Combined_dataset.csv")

In [8]:
df.head()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995,58.0,"""₹3,995.00""",INR,http://assets.myntassets.com/assets/images/837...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,...,"{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",NaN,NaN,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,"""₹1,675.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...",NaN,NaN,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",NaN,NaN,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe

In [9]:
df.shape

(1000, 24)

In [10]:
df.columns

Index(['product_id', 'title', 'product_description', 'rating', 'ratings_count',
       'initial_price', 'discount', 'final_price', 'currency', 'images',
       'delivery_options', 'product_details', 'breadcrumbs',
       'product_specifications', 'amount_of_stars', 'what_customers_said',
       'seller_name', 'sizes', 'videos', 'seller_information', 'variations',
       'best_offer', 'more_offers', 'category'],
      dtype='object')

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 24 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   product_id              1000 non-null   int64
 1   title                   1000 non-null   object
 2   product_description     1000 non-null   object
 3   rating                  1000 non-null   float64
 4   ratings_count           1000 non-null   int64
 5   initial_price           1000 non-null   int64
 6   discount                879 non-null    float64
 7   final_price             1000 non-null   object
 8   currency                1000 non-null   object
 9   images                  1000 non-null   object
 10  delivery_options        1000 non-null   object
 11  product_details         1000 non-null   object
 12  breadcrumbs             1000 non-null   object
 13  product_specifications  1000 non-null   object
 14  amount_of_stars         1000 non-null   object
 15  what_customers_said     427 non-null    object
 16  seller_name             699 non-null    object
 17  sizes                   1000 non-null   object
 18  videos                  219 non-null    object
 19  seller_information      699 non-null    object
 20  variations              438 non-null    object
 21  best_offer              1000 non-null   object
 22  more_offers             1000 non-null   object
 23  category                1000 non-null   object
dtypes: float64(2), int64(3), object(19)
memory usage: 187.6+ KB

In [12]:
df.isnull().sum()

product_id                  0
title                       0
product_description         0
rating                      0
ratings_count               0
initial_price               0
discount                  121
final_price                 0
currency                    0
images                      0
delivery_options            0
product_details             0
breadcrumbs                 0
product_specifications      0
amount_of_stars             0
what_customers_said       573
seller_name               301
sizes                       0
videos                    781
seller_information        301
variations                562
best_offer                  0
more_offers                 0
category                    0
dtype: int64

In [13]:
df.drop_duplicates(inplace=True)

In [14]:
df.columns

Index(['product_id', 'title', 'product_description', 'rating', 'ratings_count',
       'initial_price', 'discount', 'final_price', 'currency', 'images',
       'delivery_options', 'product_details', 'breadcrumbs',
       'product_specifications', 'amount_of_stars', 'what_customers_said',
       'seller_name', 'sizes', 'videos', 'seller_information', 'variations',
       'best_offer', 'more_offers', 'category'],
      dtype='object')

In [15]:
df.isnull().sum()

product_id                  0
title                       0
product_description         0
rating                      0
ratings_count               0
initial_price               0
discount                  121
final_price                 0
currency                    0
images                      0
delivery_options            0
product_details             0
breadcrumbs                 0
product_specifications      0
amount_of_stars             0
what_customers_said       573
seller_name               301
sizes                       0
videos                    781
seller_information        301
variations                562
best_offer                  0
more_offers                 0
category                    0
dtype: int64

In [16]:
df.fillna("Unknown", inplace=True)

C:\Users\Riya Saharan\AppData\Local\Temp\ipykernel_20848\839676283.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Unknown' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.fillna("Unknown", inplace=True)

In [17]:
df.drop_duplicates(inplace=True)

In [18]:
high_rating = df[df["rating"] > 4]

high_rating.head()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899,35.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,...,"{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...",Unknown,Unknown,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",Unknown,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999,65.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",Unknown,Unknown,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",Unknown,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675,52.0,"""₹1,675.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...",Unknown,Unknown,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",Unknown,Unknown,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899,17.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",Unknown,Unknown,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",Unknown,Unknown,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe
5,17198778,H&M,Beige & Tan Solid Stoneware Soap Dispenser,4.5,42,1399,Unknown,"""₹1,399.00""",INR,http://assets.myntassets.com/assets/images/171...,...,"{""1_star"":2,""2_stars"":2,""3_stars"":0,""4_stars"":...",Unknown,H &███Hen███ & █████████eta█████████████████████,"[{""size"":""Onesize""}]",Unknown,Pra███yat███fra█████████PVT███████████████████...,"[{},{}]","{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",bathroom-accessories

In [19]:
df["saved_amount"] = df["initial_price"] - df["final_price"]

TypeError: unsupported operand type(s) for -: 'int' and 'str'

In [20]:
df["initial_price"] = pd.to_numeric(df["initial_price"], errors="coerce")

df["final_price"] = pd.to_numeric(df["final_price"], errors="coerce")

In [21]:
df["saved_amount"] = df["initial_price"] - df["final_price"]

In [22]:
df[["title", "initial_price", "final_price", "saved_amount"]].head()

            title  initial_price  final_price  saved_amount
0     Lino Perros           3995          NaN           NaN
1  Tommy Hilfiger           2899          NaN           NaN
2           Lavie           2999          NaN           NaN
3          F Gear           1675          NaN           NaN
4       MYTRIDENT           2899          NaN           NaN

In [23]:
df.to_csv("cleaned_data.csv", index=False)

# Assignment Summary

- Loaded dataset using pandas
- Explored dataset structure
- Checked missing values
- Removed duplicates
- Filtered high-rated products
- Created saved_amount column
- Saved cleaned dataset